### ISSUE TITLE
Button images broken. - Themeify breaks FontAwesome icons

### ISSUE THREAD

**Issue by darthhose** [barrettford/Octoprint-Usb_keyboard#15]
I´ve got no images for the buttons. Makes it pretty hard to make new commands etc. Reinstalling does nit solve the problem.

Buttons look like this:
![Screenshot 2021-02-03 18 52 50](https://user-images.githubusercontent.com/4569335/106788318-170c5380-6651-11eb-87f9-2259e3d4b787.png)

**Comment by barrettford** [comment]
It's because you're using the Themeify plugin.  Disable the plugin, or turn it off and the icons all appear.  I don't know why, but the Themeify plugin disables the usage of fawesome button icons. (Only some of the themes, like the Discord ones, disable it, try some of the other themes to see if the button icons reappear.)

**Comment by barrettford** [comment]
This is actually a bug you should submit to the [Themeify plugin's repository.](https://github.com/birkbjo/OctoPrint-Themeify)

**Comment by darthhose** [comment]
Thanks.
